code base
Wifi-G9/frontend pull request #2
Opened 2023-11-01 17:42 UTC by martinicolaevlad

am facut file u MainPage super basic cu componentele pe care am povestit ca le vrem.

2023-11-01 18:09 UTC, bia1708 commented on g9frontend/src/components/WordSearch.tsx
> +//
Same question as above

2023-11-01 18:16 UTC, martinicolaevlad commented on g9frontend/src/components/MainPage.tsx
> +    // </div>
it was a template for me

2023-11-02 21:00 UTC, Sipos-Lucas-George commented
So just to be sure, there was nothing made in the code base, please, when you got time delete unnecessary files, such as favorite.ico, pngs etc. and make the basic routing, e.g.: "/" -> MainPage()

2023-11-03 16:42 UTC, bia1708 commented
@Sipos-Lucas-George there have been made changes to the default react project. @martinicolaevlad did a basic layout of the components. 
This is what it looks like: 
![image_2023-11-03_184225413](https://github.com/Wifi-G9/frontend/assets/89767911/a45ee42d-9b0b-4dc0-8cc0-df07ca0db59e)

2023-11-03 16:47 UTC, bia1708 commented
Also, @martinicolaevlad, when you find some time, please provide a basic README.md with the run commands for the app (i.e. `npm install` and `npm start` and whatever else is needed) and comment your code.

2023-11-03 18:08 UTC, Andrei-Fabian-Pop requested changes
Overall the project base looks good, i only had 2 questions. Apart from that I just want to mention that the react components should be small in terms of lines of code and many files, this way we will save time in the long run because everyone will work on their components and we'll be able to reuse most of them, not change the code written by someone else.

2023-11-03 18:08 UTC, Andrei-Fabian-Pop commented on g9frontend/src/components/WordSearch.tsx
> +        <div style={containerStyle} className="root-container">
You could add a folder called componentbase where you add a template for a plain component so when the tasks are assigned everyone has a starting component in which they  can solve their task. Each component should have a small size in terms of lines of code (you could specify this as a project rule). Making small components such as RootContainer that contain other components and so on will allow us to scale the project and ensure high cohesion and low coupling.

2023-11-03 18:28 UTC, bia1708 requested changes

2023-11-10 07:09 UTC, bia1708 requested changes
Before merging, you also need to solve the conflict with the README.md file.
Please sign your commits and address the requested changes. Before making the changes and signing the commits, please also consult the Contribution Rules on the organization's front page and rename the commits appropriately.
The `SearchBar` component is fine for now, but it is not finished. Later on, you will have to handle sending the searched word as a JSON to the backend.

2023-11-10 17:37 UTC, bia1708 approved these changes
Thank you for the code base, good job <3
From now on please keep your commits tidier, but that's about it.

2023-11-10 17:41 UTC, Andrei-Fabian-Pop approved these changes
Really cool stuff

2023-11-10 17:42 UTC, martinicolaevlad commented
Ly man

On Fri, 10 Nov 2023 at 19:41, Andrei ***@***.***> wrote:

> ***@***.**** approved this pull request.
>
> Really cool stuff
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Wifi-G9/frontend/pull/2#pullrequestreview-1725265828>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A6KYYQ5VLAM6VUW5D5NBNQ3YDZRMXAVCNFSM6AAAAAA6ZUS6UWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTOMRVGI3DKOBSHA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-11-10 17:43 UTC, merged