SendUsAMeessageStatus
Wifi-G9/frontend pull request #25
Opened 2023-11-18 17:57 UTC by StetcoClaudiu

2023-11-25 19:24 UTC, Andrei-Fabian-Pop requested changes

2023-11-25 19:24 UTC, Andrei-Fabian-Pop commented on g9frontend/src/components/SendUsAMessageButton/SendUsAMessageButton.tsx
> +    };
The SendUsAMessageButtonComponent should trigger a text box in which the user can type a message and after that, the box will close and the POST method will be called.

2023-11-25 19:24 UTC, Andrei-Fabian-Pop commented on g9frontend/src/components/SendUsAMessageButton/SendUsAMessageButtonStyle.css
> +}
8 rows and 9 errors, plis fix

2023-11-25 19:24 UTC, Andrei-Fabian-Pop commented on package-lock.json
> +{
please remove the package-lock.json file from your commits

2023-11-26 19:58 UTC, bia1708 commented
@Andrei-Fabian-Pop can you please confirm my last commit looks alright?

2023-11-27 12:31 UTC, Andrei-Fabian-Pop approved these changes
Looks good

2023-11-27 19:14 UTC, merged