Add codebase for User Page
Wifi-G9/frontend pull request #40
Opened 2023-12-13 19:40 UTC by Andrei-Fabian-Pop

2023-12-16 19:28 UTC, bia1708 requested changes

2023-12-16 19:28 UTC, bia1708 commented on g9frontend/src/pages/UserPage/UserPageStyle.css
> +}
The left container does not look like the figma design. It shouldn't be blue.

2023-12-16 19:28 UTC, bia1708 commented on g9frontend/src/pages/UserPage/UserPage.tsx
> +                            </Button>
This button isn't centered and frankly, it's quite ugly. There is also a lot of empty space on the left side.

2023-12-16 19:54 UTC, Andrei-Fabian-Pop commented on g9frontend/src/pages/UserPage/UserPage.tsx
> +                    </Button>
It has no icon, i replaced it with a button that takes the user to the main page

2023-12-19 20:10 UTC, bia1708 requested changes

2023-12-19 20:10 UTC, bia1708 commented on g9frontend/src/pages/UserPage/UserPageStyle.css
> +    font-size: 80px; /* Increase the font size */
The welcome text is a bit too big now.

2023-12-19 20:10 UTC, bia1708 commented on g9frontend/src/pages/UserPage/UserPage.tsx
> +                        Home Page
Please add this icon to the button: `import PersonOutlineIcon from '@mui/icons-material/PersonOutline';`, like in the Figma design.

2023-12-19 20:10 UTC, bia1708 commented on g9frontend/src/pages/UserPage/UserPageStyle.css
> +    height: 60vh; /* Optional: Set a height to center vertically within the viewport */
You should center it to be (vertically) at the center of the **left container**. Sorry if I wasn't specific enough. It's not exactly centered right now and there is too much space between the text and the 'Craft your post' button.

2023-12-19 21:31 UTC, bia1708 approved these changes

2023-12-19 21:32 UTC, merged